version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building Docker image...
      - docker build -t flask-app .
      - docker tag flask-app $DOCKERHUB_USERNAME/flask-app:latest
  post_build:
    commands:
      - echo Pushing image...
      - docker push $DOCKERHUB_USERNAME/flask-app:latest
artifacts:
  files:
    - k8s/*.yaml