version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5011:5001"

  product-service:
    build:
      context: ./product-service
    ports:
      - "5004:5002"
